name: Release new version

on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOOS: js
      GOARCH: wasm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
          cache: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build wasm
        run: |
          go build -o ${{ steps.pages.outputs.base_path }}/gosss.wasm ./cmd/webassembly/main.go
      - name: Copy go wasm js engine
        run: |
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ${{ steps.pages.outputs.base_path }}
          cp -r ./web ${{ steps.pages.outputs.base_path }}
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.pages.outputs.base_path }}
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4